In [1]:
import numpy as np

In [96]:
processo = np.array([3, 3, 3, 3, 1, 1, 1, 2])
espaco = np.array([4, 4, 4, 4])

In [97]:
# First Fit

a = 0
b = 0

while a < 4:
    # Debug ↓
    print(espaco, espaco[a], processo[b])
    if espaco[a] >= processo[b]:
        espaco[a] -= processo[b]
        b += 1
        a = 0
        if b >= processo.size:
            break
    elif a == 3 and processo[b] != 0:
        print("Problema ao alocar: ", processo[b])
        print("Posição do elemento:", list(processo).index(processo[b]))
        break
    else:
        a += 1
print("Alocação Final:", espaco)

[4 4 4 4] 4 3
[1 4 4 4] 1 3
[1 4 4 4] 4 3
[1 1 4 4] 1 3
[1 1 4 4] 1 3
[1 1 4 4] 4 3
[1 1 1 4] 1 3
[1 1 1 4] 1 3
[1 1 1 4] 1 3
[1 1 1 4] 4 3
[1 1 1 1] 1 1
[0 1 1 1] 0 1
[0 1 1 1] 1 1
[0 0 1 1] 0 1
[0 0 1 1] 0 1
[0 0 1 1] 1 1
[0 0 0 1] 0 2
[0 0 0 1] 0 2
[0 0 0 1] 0 2
[0 0 0 1] 1 2
Problema ao alocar:  2
Posição do elemento: 7
Alocação Final: [0 0 0 1]


In [ ]:
# Best Fit

a = 0
b = 0

while a < 4:
    # Debug ↓
    print(espaco, espaco[a], processo[b], np.max(espaco), list(espaco).index(np.max(espaco)))
    a += 1

In [88]:
teste = np.array([50, 25, 13, 2])
list(teste).index(np.max(teste))

[1 1 1 1]
