In [8]:
import numpy as np
import numpy.ma as ma

In [9]:
# First-Fit 

processo = np.array([2, 3, 1, 4, 2, 3, 1])
espaco = np.array([4, 4, 4, 4])
a = 0
b = 0
c = 0

while a < 4:
    # Debug ↓
    # print(espaco, espaco[a], processo[b])
    if processo[b] <= espaco[a]:
        espaco[a] -= processo[b]
        a = 0
        b += 1
        c += 1
        if b >= processo.size:
            break
    elif a == 3 and processo[b] != 0:
        print("Problema ao alocar:", processo[b])
        print("Posição:", c)
        break
    else:
        a += 1
print("Alocação Final:", espaco)

Problema ao alocar: 3
Posição: 5
Alocação Final: [1 1 0 2]


In [6]:
# Best-Fit

# x = espaco, y = processo, z = menor valor do espaco
def menorEspaco(x, y, z):
    espaco_mask = ma.masked_where(x <= y, x)
    print(espaco_mask)
#     print(np.min(espaco_mask))
    if np.min(espaco_mask) < z:
        return menorEspaco(espaco_mask, np.min(espaco_mask), z)
    if np.max(espaco_mask) < z:
        return ([-1, -1, -1, -1])
    return (espaco_mask)

processo = np.array([2, 3, 1, 2, 2, 3, 2, 2])
espaco = np.array([4, 4, 4, 4])
m = 0
    
for a in range (processo.size):
    print(espaco, np.min(espaco), processo[a])
    if processo[a] <= np.min(espaco):
        c = np.argmin(espaco)
        espaco[c] -= processo[a]
        m = 0
    else:
        espaco2 = menorEspaco(espaco, np.min(espaco), processo[a])
        c = np.argmin(espaco2)
        espaco[c] -= processo[a]
        m = 0
    for item in espaco:
        m += 1
        if item < 0:
            print(item)
            print("Erro na alocação de", processo[a])
            print("Posição de memória:", m)
            break
        print(m)

print(espaco)

[4 4 4 4] 4 2
1
2
3
4
[2 4 4 4] 2 3
[-- 4 4 4]
1
2
3
4
[2 1 4 4] 1 1
1
2
3
4
[2 0 4 4] 0 2
[2 -- 4 4]
1
2
3
4
[0 0 4 4] 0 2
[-- -- 4 4]
1
2
3
4
[0 0 2 4] 0 3
[-- -- 2 4]
[-- -- -- 4]
1
2
3
4
[0 0 2 1] 0 2
[-- -- 2 1]
[-- -- 2 --]
1
2
3
4
[0 0 0 1] 0 2
[-- -- -- 1]
[-- -- -- --]
-2
Erro na alocação de 2
Posição de memória: 1
[-2  0  0  1]


In [ ]:
#loop worst-fit
maior = espaco[0]
print(maior)
for x in range(espaco.size-1, -1, -1):
    if espaco[x] > maior:
        maior = espaco[x]
        posicao = x
print(maior, posicao)

In [23]:
espaco = np.array([4, 3, 1, 11])

espaco_mask = ma.masked_equal(espaco, np.min(espaco))

c = np.argmin(espaco)
# display(np.argmin(espaco))
print("np.min(espaco):", np.min(espaco))
print("Posição do menor valor no vetor:", c)
print("Tamanho do menor valor de memória:", espaco[c])

def menorEspaco(x, y, z):
    espaco_mask = ma.masked_where(x <= y, x)
    print(espaco_mask)
    print(np.min(espaco_mask))
    if np.min(espaco_mask) < z:
        return menorEspaco(espaco_mask, np.min(espaco_mask), z)
    return (espaco_mask)

espaco2 = menorEspaco(espaco, np.min(espaco), 11)
print(espaco2, espaco2.size)

a = np.argmin(espaco2)
display(a)

np.min(espaco): 1
Posição do menor valor no vetor: 2
Tamanho do menor valor de memória: 1
[4 3 -- 11]
3
[4 -- -- 11]
4
[-- -- -- 11]
11
[-- -- -- 11] 4


3