In [1]:
import numpy as np

In [42]:
processo = np.array([2, 3, 1, 4, 2, 3, 1])
espaco = np.array([4, 4, 4, 1])

In [27]:
# First Fit

a = 0
b = 0

while a < 4:
    # Debug ↓
    print(espaco, espaco[a], processo[b])
    if espaco[a] >= processo[b]:
        espaco[a] -= processo[b]
        b += 1
        a = 0
        if b >= processo.size:
            break
    elif a == 3 and processo[b] != 0:
        print("Problema ao alocar: ", processo[b])
        print("Posição do elemento:", list(processo).index(processo[b]))
        break
    else:
        a += 1
print("Alocação Final:", espaco)

[4 4 4 4] 4 2
[2 4 4 4] 2 3
[2 4 4 4] 4 3
[2 1 4 4] 2 1
[1 1 4 4] 1 4
[1 1 4 4] 1 4
[1 1 4 4] 4 4
[1 1 0 4] 1 2
[1 1 0 4] 1 2
[1 1 0 4] 0 2
[1 1 0 4] 4 2
[1 1 0 2] 1 3
[1 1 0 2] 1 3
[1 1 0 2] 0 3
[1 1 0 2] 2 3
Problema ao alocar:  3
Posição do elemento: 1
Alocação Final: [1 1 0 2]


In [15]:
# Best Fit

a = 0
b = 0

while a < 4:
    # Debug ↓
    print(espaco, espaco[a], processo[b], np.max(espaco), list(espaco).index(np.max(espaco)))
    a += 1

[1 1 0 0] 1 2 1 0
[1 1 0 0] 1 2 1 0
[1 1 0 0] 0 2 1 0
[1 1 0 0] 0 2 1 0


In [47]:
#loop worst-fit
maior = espaco[0]
print(maior)
for x in range(espaco.size-1, -1, -1):
    print
    if espaco[x] > maior:
        maior = espaco[x]
        posicao = x
print(maior, posicao)

4
4 3


In [50]:
#loop best-fit
menor = espaco[0]
print(maior)
for x in range(espaco.size):
    if espaco[x] < menor:
        menor = espaco[x]
        posicao = x
print(menor, posicao)

4
1 3


primeira iteracao
n = 0
armazena = posicao
if aux < sobra
espaco[0] sobra 2
sobra = aux
espaco[1] sobra 1
espaco[2] sobra 0
espaco[3] sobra 0

In [88]:
teste = np.array([50, 25, 13, 2])
list(teste).index(np.max(teste))

[1 1 1 1]
