In [1]:
import numpy as np
import numpy.ma as ma

In [109]:
# First-Fit 

processo = np.array([2, 3, 1, 4, 2, 2, 1])
espaco = np.array([4, 4, 4, 4])
a = 0 # Navegar pelo espaço/memória
b = 0 # Navegar pelos processos
c = 0 # Contador para mostrar posição do processo que teve problema ao ser alocado

while a < espaco.size:
    # Debug ↓
    print(espaco, espaco[a], processo[b])
    if processo[b] <= espaco[a]:
        espaco[a] -= processo[b]
        a = 0
        b += 1
        c += 1
        if b >= processo.size:
            break
    elif a == 3 and processo[b] > 0:
        print("Problema ao alocar:", processo[b])
        print("Posição:", c)
        break
    else:
        a += 1
print("Alocação final:", espaco)

[4 4 4 4] 4 2
[2 4 4 4] 2 3
[2 4 4 4] 4 3
[2 1 4 4] 2 1
[1 1 4 4] 1 4
[1 1 4 4] 1 4
[1 1 4 4] 4 4
[1 1 0 4] 1 2
[1 1 0 4] 1 2
[1 1 0 4] 0 2
[1 1 0 4] 4 2
[1 1 0 2] 1 2
[1 1 0 2] 1 2
[1 1 0 2] 0 2
[1 1 0 2] 2 2
[1 1 0 0] 1 1
Alocação final: [0 1 0 0]


In [93]:
def menorEspaco(x, y, z):
    ''' 
        x = espaco, y = processo, z = menor valor do espaco 
        Cria uma máscara do vetor, até o menor valor do vetor criado tenha tamanho suficiente para alocar o processo.
        Retorna um vetor mascara
    '''
    espaco_mask = ma.masked_where(x <= y, x)
    print(espaco_mask, np.min(espaco_mask))
    if np.min(espaco_mask) < z:
        return menorEspaco(espaco_mask, np.min(espaco_mask), z)
    return (espaco_mask)

In [94]:
# Best-Fit
processo = np.array([2, 3, 1, 4, 3, 2, 1])
espaco = np.array([4, 4, 4, 4])
b = 0 # Navegar pelos processos

for a in range (processo.size):
    # Debug ↓
    # print(espaco, np.min(espaco), processo[a])
    if processo[a] <= np.min(espaco):
        c = np.argmin(espaco)
        espaco[c] -= processo[a]
    else:
        espaco2 = menorEspaco(espaco, np.min(espaco), processo[a])
        c = np.argmin(espaco2)
        espaco[c] -= processo[a]
    for item in espaco:
        if item < 0:
            # Caso o primeiro valor do vetor seja negativo, é porque a função
            # menorEspaco não conseguiu um valor de tamanho suficiente para alocar o processo
            print("Erro na alocação de:", processo[a])
            print("Posição:", b)
            break
    b += 1
print("Alocação final:", espaco)

[-- 4 4 4] 4
[2 -- 4 4] 2
[-- -- 4 4] 4
[2 -- -- 4] 2
[-- -- -- 4] 4
[2 -- -- 1] 1
[2 -- -- --] 2
[-- -- -- 1] 1
Alocação final: [0 0 0 0]


In [101]:
# Worst-Fit
processo = np.array([2, 3, 1, 4, 2, 2, 1])
espaco = np.array([4, 4, 4, 4])
b = 0 # Navegar pelos processos
    
for a in range (processo.size):
    # Debug ↓
    print(espaco, np.max(espaco), processo[a])
    if processo[a] <= np.max(espaco):
        c = np.argmax(espaco)
        espaco[c] -= processo[a]
        b += 1
    else:
        print("Erro na alocação de:", processo[a])
        print("Posição:", b)
        break
print("Alocação final:", espaco)

[4 4 4 4] 4 2
[2 4 4 4] 4 3
[2 1 4 4] 4 1
[2 1 3 4] 4 4
[2 1 3 0] 3 2
[2 1 1 0] 2 2
[0 1 1 0] 1 1
Alocação final: [0 0 1 0]


In [3]:
def procura(posicao, tam):
    if posicao == tam-1:
        return 0
    else:
        posicao += 1
        return posicao

In [5]:
# Circular-Fit
processo = np.array([2, 3, 1, 4, 2, 2, 1])
espaco = np.array([4, 4, 4, 4])
a = 0 # Navegar pelo espaço/memória
b = 0 # Navegar pelos processos
c = 0 # Contador para mostrar posição do processo que teve problema ao ser alocado
aux = 0
while a < espaco.size:
    # Debug ↓
    print(espaco, espaco[a], processo[b])
    if processo[b] <= espaco[a]:
        espaco[a] -= processo[b]
        #a = 0
        b += 1
        c += 1
        a = procura(a, espaco.size)
        if b >= processo.size:
            break
    elif a == 3 and processo[b] > 1:
        print("Problema ao alocar:", processo[b])
        print("Posição:", c)
        break
    else:
        a = procura(a, espaco.size)
print("Alocação final:", espaco)

[4 4 4 4] 4 2
[2 4 4 4] 4 3
[2 1 4 4] 4 1
[2 1 3 4] 4 4
[2 1 3 0] 2 2
[0 1 3 0] 1 2
[0 1 3 0] 3 2
[0 1 1 0] 0 1
[0 1 1 0] 0 1
[0 1 1 0] 1 1
Alocação final: [0 0 1 0]
